language: objective-c
osx_image: xcode10.3

script:
- xcodebuild -project PushNotificationSimulation.xcodeproj -scheme PushNotificationSimulationExamplesTests -destination "platform=iOS Simulator,name=iPhone 8,OS=12.4" test | xcpretty -c
